List of favorites
stenington/django-sandbox pull request #3
Opened 2018-11-19 20:28 UTC by rachwyatt

@stenington

2018-11-19 21:56 UTC, stenington requested changes
Good start! I think you should just go to `localhost:8000/` to see the list of favorites though, and the page it shows should be valid HTML.

2018-11-19 23:09 UTC, rachwyatt commented
@stenington Because my html didn't have html, head and body? I get in my head that html should be simple and then realize i have no idea what i'm doing. Still need to get set up with that html validator thing you were talking about.

2018-11-27 20:09 UTC, stenington requested changes
For HTML5, the smallest valid document is apparently a `<!DOCTYPE html>` tag and then a non-empty `<title> </title>` tag. I think it's a good idea to use `<html>`, `<head>`, and `<body>` tags too though.

2018-11-27 20:09 UTC, stenington commented on favorites/templates/favorites/favorites.html
> +<html>
The first line of this file should be `<!DOCTYPE html>` for it to be valid, with your `<html>` tag on the second line.

2018-11-29 15:23 UTC, rachwyatt commented
@stenington I added the <!DOCTYPE html>

2018-11-29 19:06 UTC, stenington approved these changes

2018-11-29 19:06 UTC, merged